### ISSUE TITLE
Base64 cannot be decoded to KeyStore with Java client

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#1295]
#### Describe the bug

https://github.com/nagyesta/lowkey-vault-example/pull/444 failed because the Base64 string of the certificate cannot be decoded by the client.

#### To reproduce

1. Use v2.6.3 of Lowkey Vault
2. Fetch a certificate from Lowkey Vault
3. Try building a KeyStore from the Base64 string

#### Expected behavior

The KeyStore is working and contains the key and the cert.

#### Actual behavior

An exception is thrown:

```
java.lang.IllegalStateException: java.lang.IllegalStateException: Unable to load key store.
	at com.github.nagyesta.lowkeyvault.example.impl.AzureCertificateRepositoryImpl.getCertificate(AzureCertificateRepositoryImpl.java:33)
	at com.github.nagyesta.lowkeyvault.example.LowkeyVaultExampleApplicationTests.testCertificateRepositoryGetCertificateAndGetPrivateKeyShouldReturnGeneratedCertificateAndKeyWhenCalled(LowkeyVaultExampleApplicationTests.java:103)
...
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.IllegalStateException: Unable to load key store.
	at com.github.nagyesta.lowkeyvault.example.impl.AzureCertificateRepositoryImpl.fetchKeyStore(AzureCertificateRepositoryImpl.java:56)
	at com.github.nagyesta.lowkeyvault.example.impl.AzureCertificateRepositoryImpl.getCertificate(AzureCertificateRepositoryImpl.java:29)
	... 85 more
Caused by: java.lang.IllegalArgumentException: Illegal base64 character d
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at com.github.nagyesta.lowkeyvault.example.impl.AzureCertificateRepositoryImpl.fetchKeyStore(AzureCertificateRepositoryImpl.java:51)
	... 86 more
```

#### The command you used

N/A

#### A minimal project that can be used to reproduce the issue

See PR above

#### Environment

- OS: Any
- Version: 2.6.3
- Java version 17

#### Additional context

N/A

**Comment by nagyesta** [comment]
Relates to #1294
